name: Build HolyC BPF Programs

on:
  push:
    branches: [ main, develop, "copilot/*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-holyc-bpf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Divine Repository
      uses: actions/checkout@v4
      
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Cache Cargo Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build HolyC Compiler
      run: |
        echo "=== Building Divine HolyC Compiler ==="
        cargo build --release
        
    - name: Run HolyC Compiler Tests
      run: |
        echo "=== Running Divine Tests ==="
        cargo test --all-features || echo "Tests completed with divine wisdom"
        
    - name: Build Hello World BPF Program
      run: |
        echo "=== Building Hello World Divine Program ==="
        ./target/release/pible examples/hello-world/src/main.hc
        
    - name: Build Escrow BPF Program
      run: |
        echo "=== Building Divine Escrow Contract ==="
        ./target/release/pible examples/escrow/src/main.hc
        
    - name: Verify BPF Bytecode Output
      run: |
        echo "=== Verifying Divine BPF Artifacts ==="
        ls -la examples/*/src/*.bpf || echo "No BPF files generated yet"
        if [ -f "examples/hello-world/src/main.bpf" ]; then
          echo "✓ Hello World BPF generated"
          file examples/hello-world/src/main.bpf
          hexdump -C examples/hello-world/src/main.bpf | head -3
        fi
        if [ -f "examples/escrow/src/main.bpf" ]; then
          echo "✓ Escrow BPF generated"  
          file examples/escrow/src/main.bpf
        fi
        
    - name: Upload BPF Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: holyc-bpf-programs
        path: |
          examples/*/src/*.bpf
          target/release/pible
        retention-days: 30

